[tool.poetry]
name = "audiobook"
version = "0.1.0"
description = ""
authors = ["Robert Clayton <41345902+robert-clayton@users.noreply.github.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.scripts]
audiobook = "audiobook.__main__:main"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
transformers = ">=4.33.0,<4.41.0"
accelerate = "^0.34.2"
bitsandbytes = "^0.43.3"
numpy = "<2.0.0"
torch = [
    { url = "https://download.pytorch.org/whl/cu121/torch-2.4.0%2Bcu121-cp311-cp311-linux_x86_64.whl", markers = "sys_platform == 'linux'" },
    { url = "https://download.pytorch.org/whl/cu121/torch-2.4.0%2Bcu121-cp311-cp311-win_amd64.whl", markers = "sys_platform == 'win32'" }
]
torchaudio = [
    { url = "https://download.pytorch.org/whl/cu121/torchaudio-2.4.0%2Bcu121-cp311-cp311-linux_x86_64.whl", markers = "sys_platform == 'linux'" },
    { url = "https://download.pytorch.org/whl/cu121/torchaudio-2.4.0%2Bcu121-cp311-cp311-win_amd64.whl", markers = "sys_platform == 'win32'" }
]
torchvision = [
    { url = "https://download.pytorch.org/whl/cu121/torchvision-0.19.0%2Bcu121-cp311-cp311-linux_x86_64.whl", markers = "sys_platform == 'linux'" },
    { url = "https://download.pytorch.org/whl/cu121/torchvision-0.19.0%2Bcu121-cp311-cp311-win_amd64.whl", markers = "sys_platform == 'win32'" }
]
sentencepiece = "^0.2.0"
protobuf = "^5.28.1"
huggingface-hub = "^0.24.7"
hqq = "^0.2.2"
bs4 = "^0.0.2"
requests = "^2.32.3"
coqui-tts = "^0.24.1"
nltk = "^3.9.1"
tqdm = "^4.66.5"
python-dotenv = "^1.0.1"
diffusers = {git = "https://github.com/huggingface/diffusers.git"}
cloudscraper = "^1.2.71"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
