[tool.poetry]
name = "audiobook"
version = "0.1.0"
description = ""
authors = ["Robert Clayton <41345902+robert-clayton@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
transformers = "^4.44.2"
diffusers = { git = "https://github.com/huggingface/diffusers.git", rev = "c795c82df39620e2576ccda765b6e67e849c36e7" }
accelerate = "^0.34.2"
bitsandbytes = "^0.43.3"
numpy = "<2.0.0"
torch = { url = "https://download.pytorch.org/whl/cu121/torch-2.4.0%2Bcu121-cp311-cp311-win_amd64.whl" }
torchaudio = { url = "https://download.pytorch.org/whl/cu121/torchaudio-2.4.0%2Bcu121-cp311-cp311-win_amd64.whl" }
torchvision = { url = "https://download.pytorch.org/whl/cu121/torchvision-0.19.0%2Bcu121-cp311-cp311-win_amd64.whl" }
sentencepiece = "^0.2.0"
protobuf = "^5.28.1"
huggingface-hub = "^0.24.7"
hqq = "^0.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


